redirectsOrigin = "config"
plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "/Users/none/Library/Mobile Documents/com~apple~CloudDocs/Claude projects/Dear Future Self/public"
publishOrigin = "config"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/app"
to = "/app.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]